version: "3.8"

services:
  db:
    container_name: bago-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root

  cache:
    container_name: bago-cache
    image: redis
    ports:
      - "6379:6379"
