version: '3.1'
services:
  db:
    container_name: db-bago
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./tmp:/etc/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
