version: "3.8"

services:
  db:
    container_name: bago-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    restart: on-failure
    healthcheck:
      test: ls ~
      interval: 5s
      timeout: 10s
      retries: 2
      start_period: 10s

  mailmango:
    container_name: mailmango-container
    image: erickamorimlima/mailmango:0.0.1
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
