version: "3.8"
services:
  bago:
    build:
      context: .
    container_name: bago-server
    networks:
      - bago-net
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/root
    links:
      - "db:db"

  db:
    container_name: bago-db
    image: postgres
    ports:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    networks:
      - bago-net

networks:
  bago-net:
    driver: bridge
